# Use the official PostgreSQL slim image
FROM postgres:17-alpine

# TODO Install required extensions (to be added later when needed)


# Expose default Postgres port
EXPOSE 5432

# Use default entrypoint from base image
